spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order
          predicates:
            - Path=/ordersoe/
          uri: localhost:8081
        - id: customer
          predicates:
            - Path=/customerdata/
          uri: localhost:8082
#        - id: internal
#          predicates:
#            - Path=/process/
#          uri: localhost:8080
#        - id : auth-server
#          predicates:
#            - Path=/login/
#          uri: localhost:8088


#  main:
#    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework.web.HttpLogging: TRACE
#    reactor.netty.http.server: DEBUG
#    reactor.netty.http.client: DEBUG

#jwt:
#  secret: VHKJMNnbfhbsjkdbVJHVkhbJBKJBsmfnbngygiyguFYVHJbkjnjnsjdnlkfn

#server:
#  port: 8080

authentication:
  enabled: false